<table>
     
    <tr>
          <th>Id</th>
          <th class='thuong'>Name</th>
          <th>Url Key</th>
          <th>Post Content</th>
          <th>Feature Image</th>
    </tr>
    <form action='<?php $_PHP_SELF ?>' method="POST">
    <?php $result = $block->getEditRecord();
        print_r($result['name']);
    
    ?>
    <tr>
        <td><input type="text" name="post_id" value='<?php echo($result['post_id']) ?>'></td>
        <td><input type="text" name="name" value='<?php echo($result['name']) ?>'></td>
        <td><input type="text" name="url_key" value='<?php echo($result['url_key']) ?>'></td>
        <td><input type="text" name="post_content" value='<?php echo($result['post_content']) ?>'></td>
        <td><input type="text" name="featured_image" value='<?php echo($result['featured_image']) ?>'></td>
    </tr>
    <tr>
    <tr>
    <td><button type="submit">Update</button></td>
    <td>
    
    </td>
    </tr>
    </form>
    
    </tr>
     
</table>