<table>
    <tr>
        <th><a class="action primary"">Add Record</a></th>
    </tr>
    <tr>
        <th>Id</th>
        <th>Name</th>
        <th>Content</th>
        <th>Created At</th>
<!--        <th>Updated At</th>-->
        <th colspan="2">Action</th>
    </tr>

    <?php
    $collection = $block->getResult();
    $enable_hospital = $block->getEnable();
    if($enable_hospital){
    foreach($collection as $item){
        ?>
        <tr>
            <td><?php echo $item->getData('id_hospital'); ?></td>
            <td><?php echo $item->getData('title'); ?></td>
            <td><?php echo $item->getData('address'); ?></td>
            <td><?php echo $item->getData('telephone'); ?></td>
<!--            <td>--><?php //echo $item->getData('updated_at'); ?><!--</td>-->
            <td><a href="" class="action primary">Edit</a></td>
            <td><a href="" class="action primary">Delete</a></td>
        </tr>
    <?php }} ?>
</table>