<?php 
$record = $block->getEditRecord();

?>
<table>
     
    <tr>
          <th>Id</th>
          <th>Name</th>
          <th>Url Key</th>
          <th>Post Content</th>
          <th>Feature Image</th>
    </tr>
    <form action='<?php $_PHP_SELF ?>' method="POST">
    <tr>
        <td><input type="text" name="post_id"></td>
        <td><input type="text" name="name"></td>
        <td><input type="text" name="url_key"></td>
        <td><input type="text" name="post_content"></td>
        <td><input type="text" name="featured_image"></td>
    </tr>
    <tr>
    <tr>
    <td><button type="submit">Add</button></td>
    </tr>
    </form>
    
    </tr>
     
</table>

