<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<!-- <script src="https://www.w3schools.com/lib/w3.js"></script> -->
<div>
Bảng những post chưa được duyệt( Status = 0)
</div>
<table id="myTable"  class="w3-table-all">
    <tr>
        <th><a class="action primary" href="<?php echo $block->getUrl('helloworld/index/insert'); ?>">Add Record</a></th>
    </tr>
    <tr>
        <th style="cursor:pointer">Id</th>
        <th class='thuong' onclick='click_function()'>Name</th>
        <!-- <th onclick="click_test()">Content</th> -->
        <th onclick="sortTable(2)">Content</th>
        <th>Created At</th>
        <th>Updated At</th>
        <th>Action</th>
    </tr>

    <?php
    $collection = $block->getResult();
    foreach($collection as $item){
        ?>
        <tr>
            <td class="item"><?php echo $item->getData('post_id'); ?></td>
            <td><?php echo $item->getData('name'); ?></td>
            <td><?php echo $item->getData('post_content'); ?></td>
            <td><?php echo $item->getData('created_at'); ?></td>
            <td><?php echo $item->getData('updated_at'); ?></td>
            <td><button value=<?php echo $item->getData('post_id'); ?> class="action primary update_content">Approve</button></td>
            
        </tr>
    <?php } ?>
</table>
<button class="update_content" value="0">Show Contents</button>
<div>
Bảng những Post đã duyệt (Status = 1):<button class="hide_content">Hide Item</button>
<table class="" id="contentUpdated">
    
</table>
</div>
<!-- <div class="" id="contentUpdated"></div> -->

<ul id="sortable-list">
    <li>
        <div>
            <span>Sortable Item #1</span>
        </div>
        <input type="button" class="up" title="Up" value="Up">
        <input type="button" class="down" title="Down" value="Down">
    </li>
    <li>
        <div>
            <span>Sortable Item #2</span>
        </div>
        <input type="button" class="up" title="Up" value="Up">
        <input type="button" class="down" title="Down" value="Down">
    </li>
    <li>
        <div>
            <span>Sortable Item #3</span>
        </div>
        <input type="button" class="up" title="Up" value="Up">
        <input type="button" class="down" title="Down" value="Down">
    </li>
</ul>

<script>
     require([
        'jquery',
        'slick'
    ], function ($) {
        $(document).ready(function () {
            $(".my-list").slick({
                dots: true,
                infinite: true,
                speed: 300,
                slidesToShow: 4,
                slidesToScroll: 1
            });
        });
    });
    
    require(['test'], function(){
        $(".update_content").click(function () {
            var data_id=   $(this).attr('value');
            // alert(data_id);
            $.ajax({
                url: 'testajax',
                method: 'POST',
                data: {
                    id: data_id
                },
                success: function (data) {
                    // $('.example-element').html(data)
                    //     .trigger('contentUpdated')
                    document.getElementById('contentUpdated').innerHTML=data;
                }
            });
        });


        
        

        
    });
    require(["Mageplaza_HelloWorld/js/test_file"], function(test_file){
        });

        require([
            "jquery",
            "jquery/ui",
            "Magento_Theme/js/sortable"
        ], function ($) {
            'use strict';

            $('#sortable-list').sortable({
            axis: 'y',
            tolerance: 'pointer',
            items: 'li'
            });
        });

        function sortTable(n) {
            var table, rows, switching, i, x, y, shouldSwitch, dir, switchcount = 0;
            table = document.getElementById("myTable");
            switching = true;
            // Set the sorting direction to ascending:
            dir = "asc";
            /* Make a loop that will continue until
            no switching has been done: */
            while (switching) {
                // Start by saying: no switching is done:
                switching = false;
                rows = table.rows;
                /* Loop through all table rows (except the
                first, which contains table headers): */
                for (i = 1; i < (rows.length - 1); i++) {
                // Start by saying there should be no switching:
                shouldSwitch = false;
                /* Get the two elements you want to compare,
                one from current row and one from the next: */
                x = rows[i].getElementsByTagName("TD")[n];
                y = rows[i + 1].getElementsByTagName("TD")[n];
                /* Check if the two rows should switch place,
                based on the direction, asc or desc: */
                if (dir == "asc") {
                    if (x.innerHTML.toLowerCase() > y.innerHTML.toLowerCase()) {
                    // If so, mark as a switch and break the loop:
                    shouldSwitch = true;
                    break;
                    }
                } else if (dir == "desc") {
                    if (x.innerHTML.toLowerCase() < y.innerHTML.toLowerCase()) {
                    // If so, mark as a switch and break the loop:
                    shouldSwitch = true;
                    break;
                    }
                }
                }
                if (shouldSwitch) {
                /* If a switch has been marked, make the switch
                and mark that a switch has been done: */
                rows[i].parentNode.insertBefore(rows[i + 1], rows[i]);
                switching = true;
                // Each time a switch is done, increase this count by 1:
                switchcount ++;
                } else {
                /* If no switching has been done AND the direction is "asc",
                set the direction to "desc" and run the while loop again. */
                if (switchcount == 0 && dir == "asc") {
                    dir = "desc";
                    switching = true;
                }
                }
            }
            }
    
</script>